#!/bin/bash

MAIN=/usr/src/code/main.cpp
INPUT=/usr/src/code/input.txt

# コンパイル
g++ $MAIN -std=c++14 -I . -o .main -Wall

# コンパイルが成功したかどうかの確認
if [ $? -eq 0 ]; then
    echo "--- 実行 ---"
    ./.main < $INPUT
else
    echo "コンパイルエラー"
fi