#!/bin/bash

MAIN=/usr/src/code/main.cpp
INPUT=/usr/src/code/input.txt
TEMP=/usr/src/myapp/template.cpp

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP="/usr/src/code/log_$TIMESTAMP.cpp"

cp $MAIN $BACKUP
cp $TEMP $MAIN
cp /dev/null $INPUT
echo "記述を開始できます"
